development:
  adapter: postgresql
  encoding: utf8
  database: logbot_development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: logbot_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: logbot_production
  pool: 5